import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:4173/twse-money-flow/#/me/settings');
await p.waitForTimeout(1500);
await p.evaluate(() => new Promise((res) => { const r = indexedDB.open('twse-money-flow'); r.onsuccess = () => { const tx = r.result.transaction('watchlist','readwrite'); ['2317','2330','2454','6488','5347','3105'].forEach((code,i)=>tx.objectStore('watchlist').put({code,group:'預設',addedAt:'2026-09-01',order:i,origin:'user'})); tx.oncomplete=res; }; }));
await p.goto('http://localhost:4173/twse-money-flow/#/mine');
await p.waitForTimeout(1500);
console.log(await p.locator('.srow .sub').allTextContents());
await p.screenshot({ path: process.argv[2] });
await b.close();
